// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhybwwbhtopmeeuikkhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoeWJ3d2JodG9wbWVldWlra2hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjA2NjUsImV4cCI6MjA2NTI5NjY2NX0.pBNeHYkbEiHf-pCxFZAPIMOxZz1sCqMC5lZhgFC5tTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);