// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nythrkrfdybycrjpkans.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55dGhya3JmZHlieWNyanBrYW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MDQ0ODIsImV4cCI6MjA3NjE4MDQ4Mn0.hvJwNxqG1ZBtWaIv49in-56N_DH7uzoOCjjvvno6i_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);